# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Pull Requests Workflow

on: [pull_request]

jobs:
  qa:
    name: Quality Assurance
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        pip install flake8
        # Stop the build if there are any Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100 --statistics

    - name: psycopg2 prerequisites
      run: |
        sudo apt-get install python-dev libpq-dev

    - name: Run migrations
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run tests using pytest
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pip install pytest-django
        py.test -v
